// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-VoxTtY3xpzhVX6IaTiVf92aYjQOSQ-U',
    appId: '1:333773777821:web:751707ff62f78974a1dd74',
    messagingSenderId: '333773777821',
    projectId: 'salarymanagment',
    authDomain: 'salarymanagment.firebaseapp.com',
    storageBucket: 'salarymanagment.appspot.com',
    measurementId: 'G-NS4QKQK33P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoa0s2l1Nj9B7m_uvCHRzSNdSSpZQYdUE',
    appId: '1:333773777821:android:44907454950db772a1dd74',
    messagingSenderId: '333773777821',
    projectId: 'salarymanagment',
    storageBucket: 'salarymanagment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbk0U5I9a9I-X2oT9M7MRD-gSMakYE_SU',
    appId: '1:333773777821:ios:abae1845095e3f70a1dd74',
    messagingSenderId: '333773777821',
    projectId: 'salarymanagment',
    storageBucket: 'salarymanagment.appspot.com',
    iosBundleId: 'com.example.salaryManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbk0U5I9a9I-X2oT9M7MRD-gSMakYE_SU',
    appId: '1:333773777821:ios:a54af4759e617f56a1dd74',
    messagingSenderId: '333773777821',
    projectId: 'salarymanagment',
    storageBucket: 'salarymanagment.appspot.com',
    iosBundleId: 'com.example.salaryManagement.RunnerTests',
  );
}
